# Generated by Django 5.1.4 on 2024-12-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policereport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='policereport',
            name='name',
        ),
        migrations.AddField(
            model_name='policereport',
            name='incident_type',
            field=models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Vandalism', 'Vandalism'), ('Fraud', 'Fraud'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
